daemon:
  modules:
  - Xim
  - Wayland
  - Indicator
indicator:
  icon_color: White
log:
  global_level: DEBUG
engine:
  translation_layer: null
  default_category: Latin
  global_category_state: false
  global_hotkeys:
    M-C-Backslash:
      behavior: !Mode Math
      result: ConsumeIfProcessed
    # Super-Space:
    #   behavior: !Toggle
    #   - Hangul
    #   - Latin
    #   result: Consume
    M-C-E:
      behavior: !Mode Emoji
      result: ConsumeIfProcessed
    Esc:
      behavior: !Switch Latin
      result: Bypass
    # Muhenkan:
    #   behavior: !Toggle
    #   - Hangul
    #   - Latin
    #   result: Consume
    M-Space:
      behavior: !Toggle
      - Hangul
      - Latin
      result: Consume
    # F13:
    #   behavior: !Switch Latin
    #   result: Consume
    # F14:
    #   behavior: !Switch Hangul
    #   result: Consume
    AltR:
      behavior: Ignore
      result: Bypass
    Hangul:
      behavior: !Switch Latin
      result: Consume
    M-Hangul:
      behavior: !Switch Latin
      result: Consume
    HangulHanja:
      behavior: !Switch Hangul
      result: Consume
    M-HangulHanja:
      behavior: !Switch Hangul
      result: Consume
  category_hotkeys:
    Hangul:
      F9:
        behavior: !Mode Hanja
        result: ConsumeIfProcessed
  mode_hotkeys:
    Math:
      Enter:
        behavior: Commit
        result: ConsumeIfProcessed
      Tab:
        behavior: Commit
        result: ConsumeIfProcessed
    Hanja:
      Enter:
        behavior: Commit
        result: ConsumeIfProcessed
      Tab:
        behavior: Commit
        result: ConsumeIfProcessed
    Emoji:
      Enter:
        behavior: Commit
        result: ConsumeIfProcessed
      Tab:
        behavior: Commit
        result: ConsumeIfProcessed
  candidate_font: Noto Sans CJK KR
  xim_preedit_font:
  - Noto Sans CJK KR
  - 15.0
  latin:
    layout: Qwerty
    preferred_direct: true
  hangul:
    layout: sebeolsik-3-91
    word_commit: false
    preedit_johab: Needed
    addons:
      all:
      - ComposeChoseongSsang
      dubeolsik:
      - TreatJongseongAsChoseong
      sebeolsik-3-91:
      - FlexibleComposeOrder
