# configure release bind
release_bind = [ "KeyA", "KeyS", "KeyD", "KeyF" ]

# optional port (defaults to 4242)
port = 4242
# # optional frontend -> defaults to gtk if available
# # possible values are "cli" and "gtk"
# frontend = "gtk"

# # list of authorized tls certificate fingerprints that
# # are accepted for incoming traffic
# [authorized_fingerprints]
# "bc:05:ab:7a:a4:de:88:8c:2f:92:ac:bc:b8:49:b8:24:0d:44:b3:e6:a4:ef:d7:0b:6c:69:6d:77:53:0b:14:80" = "86o8"

# define a client on the right side with host name "iridium"
[right]
# hostname
hostname = "86o8.xtendo.org"
# activate this client immediately when lan-mouse is started
activate_on_startup = true
