- ignore: {name: "Avoid lambda using `infix`"}
- ignore: {name: "Use <$>"}
- ignore: {name: Eta reduce}
- ignore: {name: Replace case with maybe}
- ignore: {name: Use bimap}
- ignore: {name: Use const}
- ignore: {name: Use first}
- ignore: {name: Use newtype instead of data}
- ignore: {name: Use second}
- ignore: {name: Use tuple-section}
- ignore: {name: Use uncurry}
