RIGHT seek 3 exact
LEFT  seek -3 exact
Shift+RIGHT seek 10
Shift+LEFT  seek -10

Shift+p script-binding select/select-playlist

# Set playback speed to 2.0x
2 set speed 2.0
# Reset playback speed to 1.0x
1 set speed 1.0
