# ~/.config/sway/theme-dark.conf
set $bar_bg #1e1e1e
set $bar_fg #eeeeee
set $bar_sep #666666
set $ws_bg #1e1e1e
set $ws_fg #aaaaaa
set $ws_focus_bg #3a3a3a
set $ws_focus_fg #ffffff
set $urgent_bg #cc241d
set $urgent_fg #ffffff
