# ~/.config/sway/theme-light.conf
set $bar_bg #f5f5f5
set $bar_fg #222222
set $bar_sep #999999
set $ws_bg #f5f5f5
set $ws_fg #555555
set $ws_focus_bg #dddddd
set $ws_focus_fg #000000
set $urgent_bg #cc241d
set $urgent_fg #ffffff
