[Addon]
Name=Lua ESC to Default
Comment=Pressing ESC should switch to keyboard_en
Category=Module
Version=0.1
Type=Lua
OnDemand=False
Configurable=False
Library=esc_to_default.lua
Enabled=True

[Addon/Dependencies]
0=luaaddonloader

