#!/bin/sh
# sudo powertop --auto-tune &
swapon --show=SIZE | tail -n +2 | rg -q '[1-9][0-9]*[A-Z]' || sudo swapon /swapfile &

notimon &

export BROWSER=firefox
source ~/.../z13/init_monitor.sh
xrdb -merge ~/.Xresources
~/.../z13/monitor.sh

~/.../lpx/wall.sh &
~/.../z13/configure_touchpad.sh &
syndaemon -i 1 -t -k -R -d
sudo rmmod uvcvideo
xmodmap ~/.Xmodmap
pactl set-sink-mute @DEFAULT_SINK@ 1
pactl set-source-mute @DEFAULT_SOURCE@ 1

pkill xfce4-notifyd
/usr/lib/xfce4/notifyd/xfce4-notifyd &
