#!/bin/sh
# sudo powertop --auto-tune &
BROWSER=firefox
source ~/.../z13/init_monitor.sh
xrdb -merge ~/.Xresources
source ~/.../z13/monitor.sh

source ~/.../z13/configure_touchpad.sh
syndaemon -i 1 -t -k -R -d
sudo rmmod uvcvideo
xmodmap ~/.Xmodmap
pactl set-sink-mute @DEFAULT_SINK@ 1
