[general]
import = ["dimidium.toml"]

[font]
normal = { family = "Envy Code R for Powerline", style = "Regular" }
# normal = { family = "monospace", style = "Regular" }
size = 10

[window]
padding = { x = 1, y = 1 }
# padding = { x = 0, y = 0 }
