# Trigger Key
TriggerKey=
# Trigger Key for only current input context
TriggerKeyLocal=
# Hotkey for switching to the N-th input method for only current input context
SwitchKeyLocal=

[SwitchKey]
0=Hangul_Hanja
1=Hangul
2=Super+apostrophe

